Resources:

  DSGCloudHealthRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: DSG-CloudHealth
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: 'arn:aws:iam::454464851268:root'
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                "sts:ExternalId" : "da511c742b3d7a6013e3a290239eae"
  CHPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DSG-CloudWatch-Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - autoscaling:Describe*
              - aws-portal:ViewBilling
              - aws-portal:ViewUsage
              - cloudformation:ListStacks
              - cloudformation:ListStackResources
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:GetTemplate
              - cloudfront:Get*
              - cloudfront:List*
              - cloudtrail:DescribeTrails
              - cloudtrail:ListTags
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - config:Get*
              - config:Describe*
              - config:Deliver*
              - config:List*
              - cur:Describe*
              - dms:Describe*
              - dms:List*
              - dynamodb:DescribeTable
              - dynamodb:List*
              - ec2:Describe*
              - ec2:GetReservedInstancesExchangeQuote
              - ecs:List*
              - ecs:Describe*
              - elasticache:Describe*
              - elasticache:ListTagsForResource
              - elasticbeanstalk:Check*
              - elasticbeanstalk:Describe*
              - elasticbeanstalk:List*
              - elasticbeanstalk:RequestEnvironmentInfo
              - elasticbeanstalk:RetrieveEnvironmentInfo
              - elasticfilesystem:Describe*
              - elasticloadbalancing:Describe*
              - elasticmapreduce:Describe*
              - elasticmapreduce:List*
              - es:List*
              - es:Describe*
              - firehose:ListDeliveryStreams
              - firehose:DescribeDeliveryStream
              - iam:List*
              - iam:Get*
              - iam:GenerateCredentialReport
              - kinesis:Describe*
              - kinesis:List*
              - kms:DescribeKey
              - kms:GetKeyRotationStatus
              - kms:ListKeys
              - lambda:List*
              - logs:Describe*
              - redshift:Describe*
              - route53:Get*
              - route53:List*
              - rds:Describe*
              - rds:ListTagsForResource
              - s3:GetBucketAcl
              - s3:GetBucketLocation
              - s3:GetBucketLogging
              - s3:GetBucketPolicy
              - s3:GetBucketTagging
              - s3:GetBucketVersioning
              - s3:GetBucketWebsite
              - s3:List*
              - sagemaker:Describe*
              - sagemaker:List*
              - sdb:GetAttributes
              - sdb:List*
              - ses:Get*
              - ses:List*
              - sns:Get*
              - sns:List*
              - sqs:GetQueueAttributes
              - sqs:ListQueues
              - storagegateway:List*
              - storagegateway:Describe*
              - workspaces:Describe*
            Resource: "*"
      Roles:
        -
          !Ref DSGCloudHealthRole

Outputs:
  CloudHealthRoleARN:
    Description: CloudHealthRoleARN
    Value: !GetAtt DSGCloudHealthRole.Arn
